---
info:
  title: R7insight Lambdas3
  description: Lambda logging support for InsightOps
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/r7insight_lambdaS3
  x-cortex-tag: r7insight-lambdas3
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: logsearch
openapi: 3.0.1
servers:
- url: "/"
